### ISSUE TITLE
Doubts about "The Homebrew Channel"

### ISSUE THREAD

**Issue by wuniversales** [fail0verflow/hbc#12]
I just saw this project, and I find it very interesting to have an open source homebrew channel.
I have several questions to resolve.
I understand that the code is different from the official homebrew channel code.
My question about this is ..
Do I have the same characteristics and technical advantages as with the original homebrew channel (The latest version)? Do I have additional advantages?
On the other hand...
Can you launch a wad so I can install this channel?
Thank you

**Comment by marcan** [comment]
The code is only different in that it doesn't include a bunch of anti-reverse-piracy code we had to add to stop scammers from selling it.

And of course, the configuration is different by default; for example, if you want to enable automatic updates, you need to set up your own server and configure your own update URL and public key. But the code for that is in this repo, it's just disabled by default.

There is also the difference that this release works on vWii with the right display aspect ratio. That bugfix was never released in an official update, because it came too late and not too many people care.

Other than that it's the same as the official channel. However, we don't provide an installer, so you have to do that on your own.

**Comment by wuniversales** [comment]
Okay, thanks, I close this :)
