### ISSUE TITLE
Add ext4 compatibility

### ISSUE THREAD

**Issue by wuniversales** [fail0verflow/hbc#13]
Would it be possible to add compatibility to homebrew channel for ext4?
I have been able to verify that my computer with linux makes the transfers much faster to the pendrive in ext4.
Fat is a practically outdated format, and it takes a long time to make the transfers.
Cheers

**Comment by marcan** [comment]
This wouldn't be useful to add to HBC only, because homebrew itself wouldn't be able to use it to load data files.

You'd have to ask for this to be added to devkitPPC/libogc, but at this stage in the game it's rather pointless because homebrew would have to be recompiled to support it, and the scene is too dead for people to go around doing that. It's not worth it.

Additionally, FAT is much simpler than ext4. There's a reason why most smaller embedded projects use it, despite it being outdated. It is universally supported and we have compact portable libraries to read/write it that have been well tested and do not have many dependencies.

Either way, FAT shouldn't be much slower than ext4. If it is you have a configuration problem somewhere. Maybe you're mounting the filesystem in unbuffered mode by default because FAT isn't journaled. If that's the case, don't do that. Use buffering and make sure to cleanly unmount your drive before removing it.
