### ISSUE TITLE
mxml Update breaks current code

### ISSUE THREAD

**Issue by korbosoft** [fail0verflow/hbc#28]
```
source/xml.c: In function '_get_cdata':
source/xml.c:39:30: error: invalid use of incomplete typedef 'mxml_node_t' {aka 'struct _mxml_node_s'}
   39 |         mxml_node_t *n = node->child;
      |                              ^~
source/xml.c:42:22: error: invalid use of incomplete typedef 'mxml_node_t' {aka 'struct _mxml_node_s'}
   42 |                 if (n->type == MXML_OPAQUE)
      |                      ^~
source/xml.c:43:33: error: invalid use of incomplete typedef 'mxml_node_t' {aka 'struct _mxml_node_s'}
   43 |                         return n->value.opaque;
      |                                 ^~
make[3]: *** [Makefile:180: build/xml.o] Error 1
```

**Comment by carstene1ns** [comment]
The private api used here has been made private with version 3.0, the getter functions like `mxmlGetFirstChild`, `mxmlGetElement` and `mxmlGetOpaque` should be used. That being said, it should be an easy change, that is backward compatible.

**Comment by ItzSwirlz** [comment]
I've fixed it here in hbc-rebrewed: https://github.com/ItzSwirlz/hbc-rebrewed/commit/b94ef47d739451590dea3317b056e330db115daa

Additionally, removing apps will appear to throw an error because it tries using unlink on the directory instead of rmdir: https://github.com/ItzSwirlz/hbc-rebrewed/commit/361637300b5d47d4528cf9875dbe64fd168636ef
